### PR TITLE
Fix of typo

### PR DESCRIPTION
**Pull request by TomasRoj**

### CODE REVIEW

**Comment by clolsonus** [comment]
I believe the original spelling is correct "ned" refers to the north east down (ned) coordinate system.

**Comment by TomasRoj** [comment]
Sorry, Its just output from the codespell check. You are right.

**Comment by clolsonus** [comment]
No worries, glad someone cares enough to run it through a spell checker. :-)

**Comment by TomasRoj** [comment]
I did 120 pull requests to that topic today and yesterday xdd

**Pull request closed without merging**
